FOLDER = dijkstra

$(OBJ_DIR)/$(FOLDER)/dijkstra.o: $(SRC_DIR)/$(FOLDER)/dijkstra.c $(INCLUDE_DIR)/$(FOLDER)/dijkstra.h
	$(CC) $(CFLAGS) $(CPPFLAGS) -c -o $@ $<

$(OBJ_DIR)/$(FOLDER)/dijkstraV2.o: $(SRC_DIR)/$(FOLDER)/dijkstraV2.c $(INCLUDE_DIR)/$(FOLDER)/dijkstraV2.h
	$(CC) $(CFLAGS) $(CPPFLAGS) -c -o $@ $<

$(OBJ_DIR)/$(FOLDER)/speed.o: $(SRC_DIR)/$(FOLDER)/speed.c $(INCLUDE_DIR)/$(FOLDER)/speed.h
	$(CC) $(CFLAGS) $(CPPFLAGS) -c -o $@ $<