FOLDER = utils

$(OBJ_DIR)/$(FOLDER)/utils.o: $(SRC_DIR)/$(FOLDER)/utils.c $(INCLUDE_DIR)/$(FOLDER)/utils.h
	$(CC) $(CFLAGS) $(CPPFLAGS) -c -o $@ $< $(LDLIBS)

$(OBJ_DIR)/$(FOLDER)/list.o: $(SRC_DIR)/$(FOLDER)/list.c $(INCLUDE_DIR)/$(FOLDER)/list.h
	$(CC) $(CFLAGS) $(CPPFLAGS) -c -o $@ $< $(LDLIBS)

$(OBJ_DIR)/$(FOLDER)/listV2.o: $(SRC_DIR)/$(FOLDER)/listV2.c $(INCLUDE_DIR)/$(FOLDER)/listV2.h
	$(CC) $(CFLAGS) $(CPPFLAGS) -c -o $@ $< $(LDLIBS)

$(OBJ_DIR)/$(FOLDER)/array.o: $(SRC_DIR)/$(FOLDER)/array.c $(INCLUDE_DIR)/$(FOLDER)/array.h
	$(CC) $(CFLAGS) $(CPPFLAGS) -c -o $@ $< $(LDLIBS)

$(OBJ_DIR)/$(FOLDER)/follow_line.o: $(SRC_DIR)/$(FOLDER)/follow_line.c $(INCLUDE_DIR)/$(FOLDER)/follow_line.h
	$(CC) $(CFLAGS) $(CPPFLAGS) -c -o $@ $< $(LDLIBS)
